name: Feature Request
description: File a bug report
title: "[features]: "
labels: ["features"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for making a Feature Request!
  - type: textarea
    id: what-happened
    attributes:
      label: What feature do you want to request?
      description: |
        Please tell us about the feature as detailed as possible.
        Feel free to also add Media!
    validations:
      required: true
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Explain the use case or scenario in which this feature would be beneficial.
    validations:
      required: true

  - type: textarea
    id: more-information
    attributes:
      label: More information
      description: Is there anything else relevant that you want/need to share.
